### PR TITLE
Upgrade to purs v0.15

### PR DESCRIPTION
**Pull request by klntsky**
**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation in the README and/or documentation directory
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by eikooc** [comment]
Hi 👋 . Are there any obstacles to get this merged? Not trying to force anything here, just wanted some clarity on why it's lying still? 🙂

**Comment by JordanMartinez** [comment]
Maybe this repo needs to be forked?

**Comment by kejace** [comment]
Apologies for the delay - thanks for the reminder! Let me merge this today and tag the release appropriately.

**Comment by eikooc** [comment]
@kejace no worries! Looking forward to it! :tada:

**Comment by eikooc** [comment]
@kejace I'll just give you a friendly neighbourhood ping here 😉  (it's currently blocking me in updating the book, so should we go with a fork for now if you are busy?)

**Comment by eikooc** [comment]
Thanks @kejace! 🎉

**Comment by JordanMartinez** [comment]
Could a release be made, so this can be added to the package set?

**Pull request merged**
